package com.melitta.nfcgb;

import java.util.LinkedList;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;

public class EventData implements Comparable<EventData> {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
	String eventname;
	@DatabaseField
	int year;
	@DatabaseField
	boolean wintersemester;
	@DatabaseField
	String tutor;
	@DatabaseField
	String tutoremail;
	@DatabaseField
	String info;
	@DatabaseField(dataType = DataType.SERIALIZABLE)
	LinkedList<PersonData> persons = new LinkedList<PersonData>();
	@DatabaseField(dataType = DataType.SERIALIZABLE)
	LinkedList<GroupData> groups = new LinkedList<GroupData>();

	/**
	 * needed for OrmLite
	 */
	EventData() {
	}

	public EventData(String eventname, int year, boolean wintersemester, String tutor, String tutoremail, String info) {
		this.eventname = eventname;
		this.year = year;
		this.wintersemester= wintersemester;
		this.tutor= tutor;
		this.tutoremail = tutoremail;
		this.info = info;
	}

	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("eventname=").append(eventname);
		sb.append(", ").append("year=").append(year);
		sb.append(", ").append("wintersemester=").append(wintersemester);
		sb.append(", ").append("tutor=").append(tutor);
		sb.append(", ").append("tutoremail=").append(tutoremail);
		sb.append(", ").append("info=").append(info);
		return sb.toString();
	}

	@Override
	public int compareTo(EventData another) {
		if(year != another.year)
			return year - another.year;
		if(wintersemester != another.wintersemester)
			return wintersemester ? 1 : -1;
		return eventname.compareTo(another.eventname);
	}
}
