package com.melitta.nfcgb;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

public class EventData {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
	String eventname;
	@DatabaseField
	Date date;
	@DatabaseField
	String year;
	@DatabaseField
	String tutor;
	@DatabaseField
	String tutoremail;
	@DatabaseField
	String info;

	EventData() {
		// needed by ormlite
	}

	public EventData(long millis) {
		this.date = new Date(millis);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("eventname=").append(eventname);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("year=").append(year);
		sb.append(", ").append("tutor=").append(tutor);
		sb.append(", ").append("tutoremail=").append(tutoremail);
		sb.append(", ").append("info=").append(info);
		return sb.toString();
	}
}
