package com.melitta.nfcgb;

import java.io.Serializable;
import java.util.LinkedList;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class GroupData implements Serializable {
	private static final long serialVersionUID = -8620925257762834412L;
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
	String groupName;
	@DatabaseField
	int eventId;
	@DatabaseField(dataType = DataType.SERIALIZABLE)
	LinkedList<PersonData> persons = new LinkedList<PersonData>();

	GroupData() {
		// needed by ormlite
	}

	public GroupData(String groupName, int eventId) {
		this.groupName = groupName;
		this.eventId = eventId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("groupName=").append(groupName);
		sb.append(", ").append("eventId=").append(eventId);
		return sb.toString();
	}
}
