package com.melitta.nfcgb;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class PersonData {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
	String last_name;
	@DatabaseField
	Date date;
	@DatabaseField
	String first_name;
	@DatabaseField
	String email;
	@DatabaseField
	String course_of_studies;

	PersonData() {
		// needed by ormlite
	}

	public PersonData(long millis) {
		this.date = new Date(millis);
	}

	public PersonData(String firstname, String lastname, Date d, String email, String course) {
		this.first_name = firstname;
		this.last_name = lastname;
		this.date = d;
		this.email = email;
		this.course_of_studies = course;
	}
	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("first_name=").append(first_name);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("last_name=").append(last_name);
		sb.append(", ").append("email=").append(email);
		sb.append(", ").append("course_of_studies=").append(course_of_studies);
		return sb.toString();
	}
}
