package com.melitta.nfcgb;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class PersonData implements Serializable {
	private static final long serialVersionUID = 2074439586321283138L;

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	/**
	 * foreign key to event.id
	 */
	// TODO: make it to foreign key
	@DatabaseField
	int event_id;
	@DatabaseField (index = true)
	String name;
	@DatabaseField
	String email;

	// needed by ormlite
	PersonData() {
	}

	public PersonData(int event_id, String name, String email) {
		this.event_id = event_id;
		this.name = name;
		this.email = email;
	}
	

	public PersonData(String name, String email) {
		this.name = name;
		this.email = email;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("name=").append(name);
		sb.append(", ").append("email=").append(email);
		return sb.toString();
	}
}
