package com.modzelewski.nfcgb.model;

import com.j256.ormlite.field.DatabaseField;
import com.modzelewski.nfcgb.controller.ValidatorException;

public class Event implements Comparable<Event> {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private
	int id;
	@DatabaseField
	private
	String eventname;
	@DatabaseField(useGetSet = true)
	int year;
	@DatabaseField
	private
	boolean wintersemester;
	@DatabaseField
	String tutor;
	@DatabaseField
	String tutoremail;
	@DatabaseField
	private
	String info;
	/*@ForeignCollectionField(eager = false)
	ForeignCollection<PersonData> persons;
	@ForeignCollectionField(eager = false)
	ForeignCollection<GroupData> groups;*/

	/**
	 * needed for OrmLite
	 */
	public Event() {
	}

	public Event(String eventname, int year, boolean wintersemester, String tutor, String tutoremail, String info) {
		this.setEventname(eventname);
		this.year = year;
		this.setWintersemester(wintersemester);
		this.tutor = tutor;
		this.tutoremail = tutoremail;
		this.setInfo(info);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(getId());
		sb.append(", ").append("eventname=").append(getEventname());
		sb.append(", ").append("year=").append(year);
		sb.append(", ").append("wintersemester=").append(isWintersemester());
		sb.append(", ").append("tutor=").append(tutor);
		sb.append(", ").append("tutoremail=").append(tutoremail);
		sb.append(", ").append("info=").append(getInfo());
		return sb.toString();
	}

	@Override
	public int compareTo(Event another) {
		if (year != another.year)
			return year - another.year;
		if (isWintersemester() != another.isWintersemester())
			return isWintersemester() ? 1 : -1;
		return getEventname().compareTo(another.getEventname());
	}
	
	/**
	 * @return the year
	 */
	public int getYear() {
		return year;
	}

	/**
	 * @param year the year to set
	 */
	public void setYear(int year) {
		if(year < 1900 && year > 3000) {
			throw new ValidatorException("invalid Year");
		}
		this.year = year;
			
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isWintersemester() {
		return wintersemester;
	}

	public void setWintersemester(boolean wintersemester) {
		this.wintersemester = wintersemester;
	}

	public String getEventname() {
		return eventname;
	}

	public void setEventname(String eventname) {
		this.eventname = eventname;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}
