package com.modzelewski.nfcgb.model;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class GroupData implements Serializable {
	private static final long serialVersionUID = -8620925257762834412L;

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	public int id;
	@DatabaseField(index = true)
	private
	String groupName;
	@DatabaseField
	int event_id;
	/*@ForeignCollectionField(eager = false)
	ForeignCollection<PersonData> persons;*/
	private List<PersonData> person = new LinkedList<PersonData>();
	
	
	GroupData() {
		// needed by ormlite
		/*person.add(new PersonData("Hans", "hans@gmail.com"));
		person.add(new PersonData("Klaus", "klausi@gmail.com"));
		person.add(new PersonData("Egon", "egoni@gmail.com"));
		person.add(new PersonData("Waltraud", "walle@gmail.com"));*/
		
	}

	public GroupData(String groupName, int event_id) {
		super();
		this.setGroupName(groupName);
		this.event_id = event_id;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("groupName=").append(getGroupName());
		sb.append(", ").append("event_id=").append(event_id);
		return sb.toString();
	}

	public List<PersonData> getPerson() {
		return person;
	}

	public void setPerson(List<PersonData> person) {
		this.person = person;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
}
