package com.modzelewski.nfcgb.model;

import com.j256.ormlite.field.DatabaseField;

import java.io.Serializable;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class GroupMembership implements Serializable {	
	private static final long serialVersionUID = 856183608705342812L;

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	/**
	 * foreign key to event.id
	 */
	// TODO: make it to foreign key
	@DatabaseField
	private
	int group_id;
	/**
	 * foreign key to person.id
	 */
	// TODO: make it to foreign key
	@DatabaseField
	private
	int person_id;
	
	// needed by ormlite
	GroupMembership() {
	}

	public GroupMembership(int group_id, int person_id) {
		this.setGroup_id(group_id);
		this.setPersonId(person_id);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("group_id=").append(getGroup_id());
		sb.append(", ").append("person_id=").append(getPersonId());
		return sb.toString();
	}

	public int getGroup_id() {
		return group_id;
	}

	public void setGroup_id(int group_id) {
		this.group_id = group_id;
	}

	public int getPersonId() {
		return person_id;
	}

	public void setPersonId(int person_id) {
		this.person_id = person_id;
	}
}
