package com.modzelewski.nfcgb;

import java.io.Serializable;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class GroupMembershipData implements Serializable {	
	private static final long serialVersionUID = 856183608705342812L;

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	/**
	 * foreign key to event.id
	 */
	// TODO: make it to foreign key
	@DatabaseField
	int group_id;
	/**
	 * foreign key to person.id
	 */
	// TODO: make it to foreign key
	@DatabaseField
	int person_id;
	
	// needed by ormlite
	GroupMembershipData() {
	}

	public GroupMembershipData(int group_id, int person_id) {
		this.group_id = group_id;
		this.person_id = person_id;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("group_id=").append(group_id);
		sb.append(", ").append("person_id=").append(person_id);
		return sb.toString();
	}
}
